name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - 'master'
    paths:
      - 'pkgs/web/**'
      - '.github/workflows/web-*.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install
        working-directory: .

      - run: npm run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: substance-web
          directory: build
          branch: master
